name: weather
description: "An application that shows the weather of the current location."
publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  locator:
    path: 'features/locator'
  meteorologist:
    path: 'features/meteorologist'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true