name: weather
description: "An application that shows the weather of the current location."
publish_to: 'none' #

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.2
  locator:
    path: 'features/locator'
  meteorologist:
    path: 'features/meteorologist'
  go_router: ^13.0.1
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.8

flutter:
  uses-material-design: true