name: meteorologist
description: A weather module
version: 1.0.0

environment:
  sdk: ^3.2.4

dependencies:
  dio: ^5.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.7.1
  lints: ^2.1.0
  test: ^1.24.0
