name: locator
description: A module for fetching the user location
version: 1.0.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  geolocator: ^10.1.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
